  final cardInfo = {
    'diamonds2': {'value': 2, 'color': 'blue', 'suit': 'diamonds'},
    'diamonds3': {'value': 3, 'color': 'blue', 'suit': 'diamonds'},
    'diamonds4': {'value': 4, 'color': 'blue', 'suit': 'diamonds'},
    'diamonds5': {'value': 5, 'color': 'blue', 'suit': 'diamonds'},
    'diamonds6': {'value': 6, 'color': 'blue', 'suit': 'diamonds'},
    'diamonds7': {'value': 7, 'color': 'blue', 'suit': 'diamonds'},
    'diamonds8': {'value': 8, 'color': 'blue', 'suit': 'diamonds'},
    'diamonds9': {'value': 9, 'color': 'blue', 'suit': 'diamonds'},
    'diamonds10': {'value': 10, 'color': 'blue', 'suit': 'diamonds'},
    'diamondsAce': {'value': 1, 'color': 'blue', 'suit': 'diamonds'},
    'clubs2': {'value': 2, 'color': 'green', 'suit': 'clubs'},
    'clubs3': {'value': 3, 'color': 'green', 'suit': 'clubs'},
    'clubs4': {'value': 4, 'color': 'green', 'suit': 'clubs'},
    'clubs5': {'value': 5, 'color': 'green', 'suit': 'clubs'},
    'clubs6': {'value': 6, 'color': 'green', 'suit': 'clubs'},
    'clubs7': {'value': 7, 'color': 'green', 'suit': 'clubs'},
    'clubs8': {'value': 8, 'color': 'green', 'suit': 'clubs'},
    'clubs9': {'value': 9, 'color': 'green', 'suit': 'clubs'},
    'clubs10': {'value': 10, 'color': 'green', 'suit': 'clubs'},
    'clubsAce': {'value': 1, 'color': 'green', 'suit': 'clubs'},
    'hearts2': {'value': 2, 'color': 'red', 'suit': 'hearts'},
    'hearts3': {'value': 3, 'color': 'red', 'suit': 'hearts'},
    'hearts4': {'value': 4, 'color': 'red', 'suit': 'hearts'},
    'hearts5': {'value': 5, 'color': 'red', 'suit': 'hearts'},
    'hearts6': {'value': 6, 'color': 'red', 'suit': 'hearts'},
    'hearts7': {'value': 7, 'color': 'red', 'suit': 'hearts'},
    'hearts8': {'value': 8, 'color': 'red', 'suit': 'hearts'},
    'hearts9': {'value': 9, 'color': 'red', 'suit': 'hearts'},
    'hearts10': {'value': 10, 'color': 'red', 'suit': 'hearts'},
    'heartsAce': {'value': 1, 'color': 'red', 'suit': 'hearts'},
    'spades2': {'value': 2, 'color': 'black', 'suit': 'spades'},
    'spades3': {'value': 3, 'color': 'black', 'suit': 'spades'},
    'spades4': {'value': 4, 'color': 'black', 'suit': 'spades'},
    'spades5': {'value': 5, 'color': 'black', 'suit': 'spades'},
    'spades6': {'value': 6, 'color': 'black', 'suit': 'spades'},
    'spades7': {'value': 7, 'color': 'black', 'suit': 'spades'},
    'spades8': {'value': 8, 'color': 'black', 'suit': 'spades'},
    'spades9': {'value': 9, 'color': 'black', 'suit': 'spades'},
    'spades10': {'value': 10, 'color': 'black', 'suit': 'spades'},
    'spadesAce': {'value': 1, 'color': 'black', 'suit': 'spades'},
  };



