  final cardInfo = {
    'diamond2': {'value': 2, 'color': 'blue', 'suit': 'diamond'},
    'diamond3': {'value': 3, 'color': 'blue', 'suit': 'diamond'},
    'diamond4': {'value': 4, 'color': 'blue', 'suit': 'diamond'},
    'diamond5': {'value': 5, 'color': 'blue', 'suit': 'diamond'},
    'diamond6': {'value': 6, 'color': 'blue', 'suit': 'diamond'},
    'diamond7': {'value': 7, 'color': 'blue', 'suit': 'diamond'},
    'diamond8': {'value': 8, 'color': 'blue', 'suit': 'diamond'},
    'diamond9': {'value': 9, 'color': 'blue', 'suit': 'diamond'},
    'diamond10': {'value': 10, 'color': 'blue', 'suit': 'diamond'},
    'diamondAce': {'value': 1, 'color': 'blue', 'suit': 'diamond'},
    'club2': {'value': 2, 'color': 'green', 'suit': 'club'},
    'club3': {'value': 3, 'color': 'green', 'suit': 'club'},
    'club4': {'value': 4, 'color': 'green', 'suit': 'club'},
    'club5': {'value': 5, 'color': 'green', 'suit': 'club'},
    'club6': {'value': 6, 'color': 'green', 'suit': 'club'},
    'club7': {'value': 7, 'color': 'green', 'suit': 'club'},
    'club8': {'value': 8, 'color': 'green', 'suit': 'club'},
    'club9': {'value': 9, 'color': 'green', 'suit': 'club'},
    'club10': {'value': 10, 'color': 'green', 'suit': 'club'},
    'clubAce': {'value': 1, 'color': 'green', 'suit': 'club'},
    'hearts2': {'value': 2, 'color': 'red', 'suit': 'hearts'},
    'hearts3': {'value': 3, 'color': 'red', 'suit': 'hearts'},
    'hearts4': {'value': 4, 'color': 'red', 'suit': 'hearts'},
    'hearts5': {'value': 5, 'color': 'red', 'suit': 'hearts'},
    'hearts6': {'value': 6, 'color': 'red', 'suit': 'hearts'},
    'hearts7': {'value': 7, 'color': 'red', 'suit': 'hearts'},
    'hearts8': {'value': 8, 'color': 'red', 'suit': 'hearts'},
    'hearts9': {'value': 9, 'color': 'red', 'suit': 'hearts'},
    'hearts10': {'value': 10, 'color': 'red', 'suit': 'hearts'},
    'heartsAce': {'value': 1, 'color': 'red', 'suit': 'hearts'},
    'spade2': {'value': 2, 'color': 'black', 'suit': 'spade'},
    'spade3': {'value': 3, 'color': 'black', 'suit': 'spade'},
    'spade4': {'value': 4, 'color': 'black', 'suit': 'spade'},
    'spade5': {'value': 5, 'color': 'black', 'suit': 'spade'},
    'spade6': {'value': 6, 'color': 'black', 'suit': 'spade'},
    'spade7': {'value': 7, 'color': 'black', 'suit': 'spade'},
    'spade8': {'value': 8, 'color': 'black', 'suit': 'spade'},
    'spade9': {'value': 9, 'color': 'black', 'suit': 'spade'},
    'spade10': {'value': 10, 'color': 'black', 'suit': 'spade'},
    'spadeAce': {'value': 1, 'color': 'black', 'suit': 'spade'},
    'brick': {'value': 'brick', 'color': 'brick', 'suit': 'brick'}
  };



